name: Reusable A tier

on:
  workflow_call:
    inputs:
      matrix-input:
        type: string
        required: true
    
jobs:
  job-A:
    uses: ./.github/workflows/called-B.yml
    strategy:
      matrix: ${{ fromJson(inputs.matrix-input) }}
    with:
      value: ${{ matrix.key }}
